#pragma once

#include "clay.h"

#define COLOR_LIGHT (Clay_Color) { 224, 215, 210, 255 }
#define COLOR_RED (Clay_Color) { 168, 66, 28, 255 }
#define COLOR_ORANGE (Clay_Color) { 225, 138, 50, 255 }
#define COLOR_BLACK (Clay_Color) { 0, 0, 0, 255 }
#define COLOR_WHITE (Clay_Color) { 255, 255, 255, 255 }

// SIDE BAR STYLING
#define COLOR_SIDEBAR_TITLE_BACKGROUND (Clay_Color) { 180, 220, 180, 255 }
#define COLOR_SIDEBAR_TITLE_TEXT COLOR_ORANGE
#define COLOR_SIDEBAR_BACKGROUND (Clay_Color) { 80, 120, 80, 255 }
#define COLOR_SIDEBAR_TEXT COLOR_BLACK

#define PADDING_SIDEBAR_OUTER 10
#define PADDING_SIDEBAR_TITLE 10

#define GAP_SIDEBAR_INNER 10
#define GAP_SIDEBAR_TITLE 10

#define SIZE_SIDEBAR_TITLE_FONT 24
#define SIZE_SIDEBAR_TAB_STATUS 10
#define SPACING_SIDEBAR_TITLE_FONT 2

// CONNECTION TAB STYLING
#define COLOR_SIDEBAR_TAB_TEXT COLOR_BLACK
#define COLOR_SIDEBAR_TAB_ACTIVE (Clay_Color) { 160, 200, 160, 255 }
#define COLOR_SIDEBAR_TAB_HOVERED (Clay_Color) { 180, 220, 180, 255 }
#define COLOR_SIDEBAR_TAB_INACTIVE (Clay_Color) { 180, 180, 180, 200 }
#define COLOR_SIDEBAR_TAB_ACTIVE_CONNECTION (Clay_Color) { 120, 230, 120, 255 }
#define COLOR_SIDEBAR_TAB_INACTIVE_CONNECTION (Clay_Color) { 120, 120, 120, 255 }

#define SIZE_TAB_FONT 24
#define ID_TAB_FONT REGULAR_24
#define SPACING_TAB_FONT 2

#define PADDING_SIDEBAR_TAB 10


// CHAT STYLING
#define COLOR_CHAT_BACKGROUND (Clay_Color) { 55, 100, 55, 255 }
#define COLOR_CHAT_TEXT COLOR_BLACK
#define COLOR_CHAT_MESSAGE_BACKGROUND (Clay_Color) { 105, 150, 105, 255 }
#define COLOR_CHAT_SUBMIT_BUTTON COLOR_WHITE
#define COLOR_CHAT_SUBMIT_BUTTON_BACKGROUND COLOR_ORANGE
#define COLOR_CHAT_SUBMIT_BUTTON_HOVERED (Clay_Color){255, 175, 150, 255}
#define COLOR_CHAT_USER_INPUT_TEXT COLOR_BLACK

#define CORNER_RADIUS_CHAT_MESSAGE 10
#define CORNER_RADIUS_CHAT_SUBMIT_BUTTON 10

#define GAP_CHAT_MESSAGE_INNER 5
#define GAP_CHAT_MESSAGE_OUTER 10
#define GAP_CHAT_BOTTOM_BAR 10

#define ID_CHAT_FONT REGULAR_24
#define ID_CHAT_SUBMIT_BUTTON_FONT REGULAR_24
#define ID_CHAT_USER_INPUT_FONT REGULAR_24

#define PADDING_CHAT_MESSAGE_TEXT 10
#define PADDING_CHAT_USER_INPUT 10
#define PADDING_CHAT_MESSAGE_SURROUND 10
#define PADDING_CHAT_BOTTOM_BAR 10

#define SIZE_CHAT_FONT 24
#define SIZE_CHAT_SUBMIT_BUTTON_FONT 32 
#define SIZE_CHAT_USER_INPUT_FONT 24

#define PADDING_CHAT_SUBMIT_BUTTON 5

#define SIZE_CHAT_BOTTOM_BAR_TOP_BORDER 5

#define SPACING_CHAT_FONT 2
#define SPACING_CHAT_SUBMIT_BUTTON_FONT 2
#define SPACING_CHAT_USER_INPUT_FONT 1

typedef enum {
    REGULAR_24,
    MONO_16,
} FontIDs;
